-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID,  R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d")
FROM USED_GOODS_BOARD as B
JOIN USED_GOODS_REPLY as R on R.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE LIKE '%2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC